### ISSUE TITLE
All is good and excellent, but...

### ISSUE THREAD

**Issue by garex** [servo-php/fluidxml#2]
Not support 5.x :((

It was a showstopper.

**Comment by daniele-orlando** [comment]
Porting to PHP 5 is very easy. The only issue back porting is finding a satisfying solution for the `namespace()` method which is an invalid name in PHP 5.

I'm evaluating a solution.

**Comment by daniele-orlando** [comment]
PHP 5.6 is the new minimum version. Have fun! ;)

**Comment by garex** [comment]
Nice. But where is .travis.yml with tests running on both php5.6 and 7.0? You know — we are watchin for you!
![birds](https://cloud.githubusercontent.com/assets/77981/11888903/be6d5cc2-a564-11e5-842c-0a972d368a61.jpg)

**Comment by daniele-orlando** [comment]
Checkout the last commit! ;)

**Thanks for the feedback**. <3

**Comment by daniele-orlando** [comment]
Closed by 1dada3c.

**Comment by garex** [comment]
))
