### ISSUE TITLE
second iteration inside first one

### ISSUE THREAD

**Issue by muzunov** [servo-php/fluidxml#20]
Hi Daniele. I as wondering how add second iteration inside first one, i red documentation but i cant do that. Like in your example, i  fetch data like author and book from mysql make iteration, but every book has a images stored in other table and i make another query. I try but..... errors :)

**Comment by daniele-orlando** [comment]
Sorry for the late replay but I was away.

If you could post an excerpt of your code I could understand what is not working in your specific case.
