### ISSUE TITLE
CDATA?

### ISSUE THREAD

**Issue by tolgaulas** [servo-php/fluidxml#4]
Great work. When do you plan for the CDATA nodes? (?Perhaps a workaround with domdocument?)

**Comment by daniele-orlando** [comment]
Thank you!
Cdata support is already there. 
Check the `->appendCdata()` method and its concise alias `->cdata()`.

**Comment by tolgaulas** [comment]
Yey! Maybe documentation is missing. Thank you.

Best regards.

--
Tolga Ulas
+905337464908, skype:tolgaulas

**Comment by daniele-orlando** [comment]
All available methods are listed inside `documents/API.md`.

I missed to include `->cdata()`, but `->appendCdata()` together with `->appendSibling()`, `->prependChild()` etc. are listed there.
