### ISSUE TITLE
ñ, Ñ using UTF8 break the document

### ISSUE THREAD

**Issue by VictorManuelSarmiento** [servo-php/fluidxml#40]
Using a string in UTF8 with ñ / Ñ breaks the document:

- **Code:**

          `$property_label->add('Street', true)->cdata($property->address);`

- **Result:**

         ` <Street><![CDATA[Calle Salamanca, Espa￿----------------------------------^`

- **Original text:** 
         Calle Salamanca, España

Check in PHP with **mb_detect_encoding** -> "UTF-8"

Thanks.

**Comment by daniele-orlando** [comment]
Hi dear @VictorManuelSarmiento and thanks for reporting you issue.

As you may know, FluidXML uses as its foundation DOMDocument, which is configured by FluidXML to deal with UTF-8 strings.

To better understand your issue, I would propose you to try reproducing the same issue with DOMDocument to see if it is a DOMDocument related issue, a FluidXML bug or a particular situation of your PHP configuration.

```php
$dom = new \DOMDocument('1.0', 'UTF-8');
$dom->formatOutput       = true;
$dom->preserveWhiteSpace = false;

$street = $dom->createElement('Street');
$street->appendChild(new \DOMCDATASection($utf8String));

$dom->appendChild($street);

print $xml->saveXML();
```

Are you experiencing the same encoding issue with this configuration?
