### ISSUE TITLE
Error when converting array of strings to XML

### ISSUE THREAD

**Issue by denormalizer** [servo-php/fluidxml#48]
I'm trying to convert an array of strings to XML.

I get "Invalid Character Error" when calling `addChild()`:

    $arrA = array('abc 123', 'def 456');
    $xml = new FluidXml();
    $xml->addChild($return);

    <exception class="DOMException" message="Invalid Character Error">

When removing the space, the exception is not thrown:

    <?xml version="1.0" encoding="UTF-8"?>
    <doc>
        <abc123/>
        <def456/>
    </doc>

I'm expecting something like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <doc>
        <idx>abc 123</idx>
        <idx>def 456</idx>
    </doc>

I know I can achieve that with the following:

    $xml = new FluidXml();
    $xml->add('idx', 'abc 123');
    $xml->add('idx', 'def 456');

However, I was hoping FluidXml can do it automagically for me.

Is there a solution/workaround I can use?

**Comment by daniele-orlando** [comment]
FluidXml has a well defined protocol on how it handles the array and your expressed case is quite uncommon/exceptional compared to the general pattern of an array of strings.

What you should do is mapping your array to the XML structure you want:
```php
$list = [ 'abc 123', 'def 456' ];
$items = array_map(function ($it) { return [ 'idx' => $it ];  }, $list);
$xml->addChild($items);
```

**Comment by denormalizer** [comment]
Thanks for your response. It has been useful.
