### ISSUE TITLE
& symbole issue when we have & syomble the Xml become invalid

### ISSUE THREAD

**Issue by syedaliraza102** [servo-php/fluidxml#57]
& symbole kindly fix this thing. When we have & sysmbole then the xml is broken

**Comment by daniele-orlando** [comment]
It's by [XML Spec](https://www.w3.org/TR/xml/):

> The ampersand character (&) and the left angle bracket (<) must not appear in their literal form ... they must be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively. The right angle bracket (>) may be represented using the string " &gt; ", and must, for compatibility, be escaped using either " &gt; " 

As so, thei must be escaped before being inserted inside an XML document.

**Comment by syedaliraza102** [comment]
Yes this things needs to handle by library it self .
$book = new FluidXml();
$book->add($xmlstr);

I am just passing the array in it . It needs to filter it self by library
