### ISSUE TITLE
What is the module need to use this?

### ISSUE THREAD

**Issue by yothin** [servo-php/fluidxml#7]
I can't use fluidxml on production and display error message 

Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /xxx/xxx/xxx/public_html/trueorfalse/FluidXml/FluidInterface.php on line 15 

On line 15 have method         public function query(...$query); i thank the php unknow ... on prefix $query
       
 but my local worked perfectly. 

Thank you

**Comment by daniele-orlando** [comment]
FluidXML requires PHP 5.6 or higher. Your are using on the production server a lower version.
