### ISSUE TITLE
How to pretty print added nodes?

### ISSUE THREAD

**Issue by FoxxMD** [servo-php/fluidxml#9]
I'm trying to add new nodes to an existing document using `add()` and, while it works, the output from `->xml()` is no long structured. The rest of the document (where I'm just doing `setText()`) looks fine. The XML outputted is also valid -- is there some other method I should be using to keep this structured?

```php
$orderXml = FluidXml::load($this->orderTemplate);

$productsXml = [];
foreach ($order->toPackingSlipItems() as $item) {

    $productXmlDoc = FluidXml::load($this->productTemplate);
    $productXml    = $productXmlDoc->query('//product');

    $productXml->query('//product_id')->setText($item->product->getId());
    $productXml->query('//name')->setText($item->getName());
    $productXml->query('//qty')->setText($item->quantity);

    $productsXml[] = $productXml;
}

$productsNode = $orderXml->query('//products');
foreach ($productsXml as $pXml) {
    $productsNode->add($pXml);
}

$orderXml->xml();
```

The output of `$orderXml->xml()` looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<order>
  <order_id_prefix>8612963</order_id_prefix>
  <order_id>8612963</order_id>
  <order_date>2016-04-19</order_date>
  <customer_id>12238189</customer_id>
  <title/>
  <firstname>Georgia</firstname>
...
  <msg>50108</msg>
  <products>
    <product><product_id>13305</product_id><name>AAAAA</name><qty>4</qty><unit_price>0.00</unit_price><total_price>0.00</total_price></product><product><product_id>1944</product_id><name>BBBBB</name><qty>1</qty><unit_price>0.00</unit_price><total_price>0.00</total_price></product><product><product_id>2371</product_id><name>CCCCC</name><qty>1</qty><unit_price>0.00</unit_price><total_price>0.00</total_price></product></products>
</order>
```

**Comment by daniele-orlando** [comment]
Uhm, interesting. Actually I don't know but I will investigate. In the meantime I suggest you to refactor your code, fixing the formatting problem too.

```php
$orderXml = FluidXml::load($this->orderTemplate);
$products = $orderXml->query('//products');

foreach ($order->toPackingSlipItems() as $item) {
    $products->add('product', true)
                ->add('product_id', $item->product->getId())
                ->add('name', $item->getName())
                ->add('qty', $item->quantity);
    }
```

Pretty simple. Less code, more readable, no formatting problem, better performances.

**Comment by Cristo-Conklin** [comment]
Can fluidxml store on array an xml and output the exact information afterwards?
I mean, is totally loseless , will the output be the exact same file, crc checked?
If not, does it differs only in the pretty printing (all attributes, etc are kept)?

Thanks

**Comment by daniele-orlando** [comment]
@Cristo-Conklin FluidXm'sl array syntax for creating nodes doesn't support cdata, comments, and indentation is fixed. So generally you can generate an XML with the same digest of an existing XML, but you have to pay attention to these limitations.

**Comment by Cristo-Conklin** [comment]
Excluding those: no need for cdata and comments and indentation.
We can assume the rest of the data's integrity, all atributes, like:
` <text xml:space="preserve">`
`      <namespace key="-2">Media</namespace>`

Can be saved and retrieved back the same content as the original?

I understand that you solved the same key issue of the approaches like [this](http://www.xml.com/pub/a/2006/05/31/converting-between-xml-and-json.html?page=3) in a better way than [jsonml](http://www.jsonml.org/) for what I see in your docs. Is that right?

**Comment by daniele-orlando** [comment]
Yes, the same content can be retrieved.
If you find some edge cases or issues, report them as issues or create a pull-request.

**Comment by daniele-orlando** [comment]
@FoxxMD, did it solve your problem?

**Comment by FoxxMD** [comment]
@daniele-orlando Apologies for my absence, I was away on a long weekend vacation 😀

I did manage to find the problem and correct the lack of structure, however your refactor did not make a difference!

I tried your refactor but the output remained the same -- so I went back to the file loaded into `$this->orderTemplate` to see if there was any funny business. I found that the xml looked like this:

```xml
<order>
  <order_id_prefix></order_id_prefix>
  <order_id></order_id>
  <order_date></order_date>
  <customer_id></customer_id>
  <title/>
  <firstname></firstname>
...
  <msg></msg>
  <products>
  </products>
</order>
```

Removing the newline between the `products` node

```xml
<products></products>
```

then produced the correctly structured output!

So I'm not sure if this is a valid issue anymore. Although the original document, with the newline, is valid XML it's not "pretty printed" XML. If this is expected behavior perhaps adding a note in the [importing](https://github.com/servo-php/fluidxml/wiki/Getting-Started:-11.-Importing) section of the docs would be useful. Of course this might have also been a non-issue had I loaded in my original file using simplexml first?

What do you think?

**Comment by daniele-orlando** [comment]
Quite interesting. Thank you very much for reporting your experience, I'm sure it will help other people in future.

This is an edge case of valid XML files but not well formatted that I need to investigate. Actually FluidXML has no responsibilities in the formatting of the output document because everything about formatting is handled internally by the PHP native implementation of DOMDocument. I have to comb through the PHP mailing list to discover more about this odd behavior of the XML formatting.
As you suggested, anything relevant will be documented in the Importing section of the wiki.

Again, thank you very much!

**Comment by daniele-orlando** [comment]
http://php.net/manual/it/class.domdocument.php#96055

**Comment by FoxxMD** [comment]
Not surprised in the slightest! PHP isn't exactly the most consistent language.
